#!/usr/bin/env bash

declare -ag HARD_TIMEOUT_ACTIVE_PIDS=()
declare -ag HARD_TIMEOUT_ACTIVE_PGIDS=()
declare -ag HARD_TIMEOUT_ACTIVE_RECORDS=()
declare -ag HARD_TIMEOUT_ACTIVE_START_TIMES=()
declare -ag HARD_TIMEOUT_ACTIVE_BOOT_IDS=()
declare -ag HARD_TIMEOUT_ACTIVE_PID_NAMESPACES=()
HARD_TIMEOUT_LAST_RECORD=""
HARD_TIMEOUT_LAST_START_TIME=""
HARD_TIMEOUT_LAST_BOOT_ID=""
HARD_TIMEOUT_LAST_PID_NAMESPACE=""
HARD_TIMEOUT_OWNER_LEASE=""
HARD_TIMEOUT_OWNER_START_TIME=""
HARD_TIMEOUT_OWNER_BOOT_ID=""
HARD_TIMEOUT_OWNER_PID_NAMESPACE=""

validate_hard_timeout_registry() {
	local root="${HARD_TIMEOUT_REGISTRY_ROOT:-}"
	if [[ -z "$root" || ! -d "$root" || -L "$root" ]]; then
		echo "Timeout registry is missing or is not a real directory: ${root:-<unset>}" >&2
		return 1
	fi
	local probe=""
	if ! probe="$(mktemp "$root/.handshake.XXXXXX")"; then
		echo "Timeout registry is not writable: $root" >&2
		return 1
	fi
	local nonce="${BASHPID}-$(date +%s%N)"
	local observed=""
	if ! printf '%s\n' "$nonce" > "$probe" || ! IFS= read -r observed < "$probe" || [[ "$observed" != "$nonce" ]]; then
		rm -f "$probe"
		echo "Timeout registry handshake failed: $root" >&2
		return 1
	fi
	rm -f "$probe"
}

ensure_hard_timeout_registry() {
	if [[ -n "${HARD_TIMEOUT_REGISTRY_ROOT:-}" ]]; then
		validate_hard_timeout_registry || return 1
		claim_hard_timeout_registry_owner
		return $?
	fi
	local registry_parent="${HARD_TIMEOUT_REGISTRY_PARENT:-${TMPDIR:-/tmp}}"
	mkdir -p "$registry_parent" || return 1
	HARD_TIMEOUT_REGISTRY_ROOT="$(mktemp -d "$registry_parent/xenogenesis-timeout-registry.XXXXXX")" || return 1
	HARD_TIMEOUT_REGISTRY_OWNER_PID="$BASHPID"
	export HARD_TIMEOUT_REGISTRY_ROOT HARD_TIMEOUT_REGISTRY_OWNER_PID
	validate_hard_timeout_registry || return 1
	claim_hard_timeout_registry_owner
}

claim_hard_timeout_registry_owner() {
	if [[ -n "$HARD_TIMEOUT_OWNER_LEASE" && -f "$HARD_TIMEOUT_OWNER_LEASE" ]]; then
		return 0
	fi
	local owner_pid="$BASHPID"
	local identity=""
	identity="$(read_process_identity "$owner_pid")" || return 1
	local boot_id pid_namespace start_time
	read -r boot_id pid_namespace start_time <<< "$identity"
	local lock_fd
	exec {lock_fd}<"$HARD_TIMEOUT_REGISTRY_ROOT" || return 1
	flock -x "$lock_fd" || {
		exec {lock_fd}<&-
		return 1
	}
	local lease="$HARD_TIMEOUT_REGISTRY_ROOT/.owner.$owner_pid.$start_time"
	local temporary=""
	temporary="$(mktemp "$HARD_TIMEOUT_REGISTRY_ROOT/.owner-record.XXXXXX")" || {
		exec {lock_fd}<&-
		return 1
	}
	if ! printf 'v1 %s %s %s %s\n' "$owner_pid" "$boot_id" "$pid_namespace" "$start_time" > "$temporary" || \
		! mv "$temporary" "$lease"; then
		rm -f "$temporary"
		exec {lock_fd}<&-
		return 1
	fi
	HARD_TIMEOUT_OWNER_LEASE="$lease"
	HARD_TIMEOUT_OWNER_START_TIME="$start_time"
	HARD_TIMEOUT_OWNER_BOOT_ID="$boot_id"
	HARD_TIMEOUT_OWNER_PID_NAMESPACE="$pid_namespace"
	exec {lock_fd}<&-
}

release_hard_timeout_registry_owner() {
	if [[ -n "$HARD_TIMEOUT_OWNER_LEASE" ]]; then
		rm -f "$HARD_TIMEOUT_OWNER_LEASE"
	fi
	HARD_TIMEOUT_OWNER_LEASE=""
	HARD_TIMEOUT_OWNER_START_TIME=""
	HARD_TIMEOUT_OWNER_BOOT_ID=""
	HARD_TIMEOUT_OWNER_PID_NAMESPACE=""
}

restore_hard_timeout_signal_trap() {
	local signal_name="$1"
	local declaration="$2"
	if [[ -n "$declaration" ]]; then
		# trap -p emits shell-quoted input generated by Bash itself.
		eval "$declaration"
	else
		trap - "$signal_name"
	fi
}

forward_hard_timeout_signal() {
	local signal_name="$1"
	[[ -n "$signal_name" ]] || return 0
	kill -s "$signal_name" "$BASHPID"
	case "$signal_name" in
		TERM) return 143 ;;
		INT) return 130 ;;
		*) return 1 ;;
	esac
}

promote_pending_timeout_identity() {
	local pending_record="$1"
	local supervisor_pid="$2"
	local supervisor_pgid="$3"
	local supervisor_boot="$4"
	local supervisor_namespace="$5"
	local supervisor_start="$6"
	validate_hard_timeout_registry || return 1
	local temporary=""
	temporary="$(mktemp "$HARD_TIMEOUT_REGISTRY_ROOT/.pending-record.XXXXXX")" || return 1
	if ! printf 'v2 %s %s %s %s %s %s %s %s %s\n' \
		"$BASHPID" "$HARD_TIMEOUT_OWNER_BOOT_ID" "$HARD_TIMEOUT_OWNER_PID_NAMESPACE" \
		"$HARD_TIMEOUT_OWNER_START_TIME" "$supervisor_pid" "$supervisor_pgid" \
		"$supervisor_boot" "$supervisor_namespace" "$supervisor_start" > "$temporary" || \
		! mv "$temporary" "$pending_record"; then
		rm -f "$temporary"
		return 1
	fi
}

demote_pending_timeout_identity() {
	local pending_record="$1"
	validate_hard_timeout_registry || return 1
	local temporary=""
	temporary="$(mktemp "$HARD_TIMEOUT_REGISTRY_ROOT/.pending-record.XXXXXX")" || return 1
	if ! printf 'v1 %s %s %s %s\n' "$BASHPID" "$HARD_TIMEOUT_OWNER_BOOT_ID" \
		"$HARD_TIMEOUT_OWNER_PID_NAMESPACE" "$HARD_TIMEOUT_OWNER_START_TIME" > "$temporary" || \
		! mv "$temporary" "$pending_record"; then
		rm -f "$temporary"
		return 1
	fi
}

process_exists() {
	local pid="$1"
	kill -0 "$pid" 2>/dev/null
}

process_group_exists() {
	local pgid="$1"
	kill -0 -- "-$pgid" 2>/dev/null
}

read_process_stat_fields() {
	local pid="$1"
	local stat_line=""
	if [[ ! "$pid" =~ ^[1-9][0-9]*$ ]] || ! { IFS= read -r stat_line < "/proc/$pid/stat"; } 2>/dev/null; then
		return 1
	fi
	local fields="${stat_line##*) }"
	local -a values=()
	read -r -a values <<< "$fields"
	if [[ "${#values[@]}" -lt 20 ]]; then
		return 1
	fi
	printf '%s %s %s %s\n' "${values[2]}" "${values[3]}" "${values[19]}" "${values[0]}"
}

read_process_identity() {
	local pid="$1"
	local boot_id=""
	local pid_namespace=""
	local stat_fields=""
	if ! IFS= read -r boot_id < /proc/sys/kernel/random/boot_id || \
		! pid_namespace="$(readlink "/proc/$pid/ns/pid")" || \
		! stat_fields="$(read_process_stat_fields "$pid")"; then
		return 1
	fi
	local pgrp session start_time state
	read -r pgrp session start_time state <<< "$stat_fields"
	if [[ ! "$boot_id" =~ ^[0-9a-fA-F-]+$ || ! "$pid_namespace" =~ ^pid:\[[0-9]+\]$ || ! "$start_time" =~ ^[0-9]+$ ]]; then
		return 1
	fi
	printf '%s %s %s\n' "$boot_id" "$pid_namespace" "$start_time"
}

process_identity_matches() {
	local pid="$1"
	local expected_boot="$2"
	local expected_namespace="$3"
	local expected_start="$4"
	local actual=""
	actual="$(read_process_identity "$pid")" || return 1
	[[ "$actual" == "$expected_boot $expected_namespace $expected_start" ]]
}

timeout_identity_confirmed_gone() {
	local pid="$1"
	local expected_boot="$2"
	local expected_namespace="$3"
	local expected_start="$4"
	if [[ ! -d "/proc/$pid" ]]; then
		return 0
	fi
	local actual=""
	if ! actual="$(read_process_identity "$pid")"; then
		return 2
	fi
	[[ "$actual" != "$expected_boot $expected_namespace $expected_start" ]]
}

group_identity_matches() {
	local leader_pid="$1"
	local pgid="$2"
	local expected_boot="$3"
	local expected_namespace="$4"
	local expected_start="$5"
	local current_boot=""
	IFS= read -r current_boot < /proc/sys/kernel/random/boot_id || return 1
	[[ "$current_boot" == "$expected_boot" ]] || return 1
	if process_exists "$leader_pid"; then
		process_identity_matches "$leader_pid" "$expected_boot" "$expected_namespace" "$expected_start" || return 1
		local leader_fields=""
		leader_fields="$(read_process_stat_fields "$leader_pid")" || return 1
		local leader_pgrp leader_session leader_start leader_state
		read -r leader_pgrp leader_session leader_start leader_state <<< "$leader_fields"
		[[ "$leader_pgrp" == "$pgid" && "$leader_session" == "$pgid" && "$leader_start" == "$expected_start" ]]
		return $?
	fi
	# A process group ID is reusable. Once its authenticated session leader is
	# gone, membership alone cannot prove that the current group is the one we
	# registered, so group-directed signaling is forbidden.
	return 1
}

read_process_group() {
	local pid="$1"
	local pgid=""
	local attempt
	for attempt in $(seq 1 100); do
		pgid="$(ps -o pgid= -p "$pid" 2>/dev/null | tr -d ' ')"
		if [[ "$pgid" == "$pid" ]]; then
			printf '%s\n' "$pgid"
			return 0
		fi
		if ! process_exists "$pid" && process_group_exists "$pid"; then
			printf '%s\n' "$pid"
			return 0
		fi
		if ! process_exists "$pid" && ! process_group_exists "$pid"; then
			return 1
		fi
		sleep 0.01
	done
	return 1
}

reap_direct_child_if_zombie() {
	local pid="$1"
	local state=""
	state="$(ps -o stat= -p "$pid" 2>/dev/null | tr -d ' ')"
	if [[ "$state" == Z* ]]; then
		wait "$pid" 2>/dev/null || true
	fi
}

terminate_unregistered_timeout_child() {
	local pid="$1"
	local grace_seconds="$2"
	local deadline_ns=$(( $(date +%s%N) + grace_seconds * 1000000000 ))
	# Before the supervisor receives its acknowledgement it cannot start the
	# payload. The shell still owns this exact direct child even if /proc could
	# not provide a durable identity, so never fall back to an unauthenticated
	# process-group signal here.
	kill -USR1 "$pid" 2>/dev/null || true
	while process_exists "$pid"; do
		reap_direct_child_if_zombie "$pid"
		process_exists "$pid" || break
		if (( $(date +%s%N) >= deadline_ns )); then
			break
		fi
		sleep 0.02
	done
	if process_exists "$pid"; then
		kill -KILL "$pid" 2>/dev/null || true
	fi
	wait "$pid" 2>/dev/null || true
	if process_exists "$pid"; then
		echo "Failed to reap unregistered timeout child: pid=$pid" >&2
		return 1
	fi
}

wait_for_timeout_tree_exit() {
	local pid="$1"
	local pgid="$2"
	local wait_seconds="$3"
	local deadline_ns=$(( $(date +%s%N) + wait_seconds * 1000000000 ))
	while true; do
		reap_direct_child_if_zombie "$pid"
		if ! process_exists "$pid" && ! process_group_exists "$pgid"; then
			return 0
		fi
		if (( $(date +%s%N) >= deadline_ns )); then
			return 1
		fi
		sleep 0.02
	done
}

wait_for_process_group_exit() {
	local pgid="$1"
	local wait_seconds="$2"
	local deadline_ns=$(( $(date +%s%N) + wait_seconds * 1000000000 ))
	while process_group_exists "$pgid"; do
		if (( $(date +%s%N) >= deadline_ns )); then
			return 1
		fi
		sleep 0.02
	done
}

timeout_group_has_live_member_except() {
	local leader_pid="$1"
	local pgid="$2"
	local proc_dir=""
	local member_pid=""
	local fields=""
	local member_pgrp member_session member_start member_state
	for proc_dir in /proc/[0-9]*; do
		member_pid="${proc_dir#/proc/}"
		[[ "$member_pid" == "$leader_pid" ]] && continue
		fields="$(read_process_stat_fields "$member_pid")" || continue
		read -r member_pgrp member_session member_start member_state <<< "$fields"
		if [[ "$member_pgrp" == "$pgid" && "$member_state" != "Z" ]]; then
			return 0
		fi
	done
	return 1
}

wait_for_timeout_group_members_exit() {
	local leader_pid="$1"
	local pgid="$2"
	local wait_seconds="$3"
	local deadline_ns=$(( $(date +%s%N) + wait_seconds * 1000000000 ))
	while timeout_group_has_live_member_except "$leader_pid" "$pgid"; do
		if (( $(date +%s%N) >= deadline_ns )); then
			return 1
		fi
		sleep 0.02
	done
}

# Test cleanup uses this only for process groups created by the same gate run.
terminate_process_group() {
	local pgid="$1"
	local grace_seconds="$2"
	if ! process_group_exists "$pgid"; then
		return 0
	fi
	kill -TERM -- "-$pgid" 2>/dev/null || true
	if wait_for_process_group_exit "$pgid" "$grace_seconds"; then
		return 0
	fi
	kill -KILL -- "-$pgid" 2>/dev/null || true
	if wait_for_process_group_exit "$pgid" "$grace_seconds"; then
		return 0
	fi
	echo "Failed to reap timeout process group: pgid=$pgid" >&2
	return 1
}

verify_timeout_target() {
	local pid="$1"
	local pgid="$2"
	local boot_id="$3"
	local pid_namespace="$4"
	local start_time="$5"
	if ! process_exists "$pid" && ! process_group_exists "$pgid"; then
		return 3
	fi
	group_identity_matches "$pid" "$pgid" "$boot_id" "$pid_namespace" "$start_time"
}

terminate_timeout_identity() {
	local pid="$1"
	local pgid="$2"
	local boot_id="$3"
	local pid_namespace="$4"
	local start_time="$5"
	local grace_seconds="$6"
	local identity_status=0
	verify_timeout_target "$pid" "$pgid" "$boot_id" "$pid_namespace" "$start_time" || identity_status=$?
	if [[ "$identity_status" -eq 3 ]]; then
		wait "$pid" 2>/dev/null || true
		return 0
	fi
	if [[ "$identity_status" -ne 0 ]]; then
		echo "Discarded stale timeout identity before TERM: pid=$pid pgid=$pgid" >&2
		return 2
	fi
	if [[ "${HARD_TIMEOUT_TEST_TERMINATION_FAILURE_PID:-}" == "$pid" ]]; then
		echo "Injected timeout termination failure before TERM: pid=$pid pgid=$pgid" >&2
		return 1
	fi
	kill -TERM -- "-$pgid" 2>/dev/null || true
	if wait_for_timeout_group_members_exit "$pid" "$pgid" "$grace_seconds"; then
		if ! process_identity_matches "$pid" "$boot_id" "$pid_namespace" "$start_time"; then
			echo "Discarded stale timeout identity before supervisor exit: pid=$pid pgid=$pgid" >&2
			return 2
		fi
		kill -USR1 "$pid" 2>/dev/null || true
		if wait_for_timeout_tree_exit "$pid" "$pgid" "$grace_seconds"; then
			wait "$pid" 2>/dev/null || true
			return 0
		fi
	fi
	identity_status=0
	verify_timeout_target "$pid" "$pgid" "$boot_id" "$pid_namespace" "$start_time" || identity_status=$?
	if [[ "$identity_status" -eq 3 ]]; then
		wait "$pid" 2>/dev/null || true
		return 0
	fi
	if [[ "$identity_status" -ne 0 ]]; then
		echo "Discarded stale timeout identity before KILL: pid=$pid pgid=$pgid" >&2
		return 2
	fi
	kill -KILL -- "-$pgid" 2>/dev/null || true
	if wait_for_timeout_tree_exit "$pid" "$pgid" "$grace_seconds"; then
		wait "$pid" 2>/dev/null || true
		return 0
	fi
	echo "Failed to reap timeout identity: pid=$pid pgid=$pgid" >&2
	return 1
}

register_timeout_process() {
	local gate_name="$1"
	local pid="$2"
	local pgid="$3"
	local identity=""
	identity="$(read_process_identity "$pid")" || return 1
	local boot_id pid_namespace start_time
	read -r boot_id pid_namespace start_time <<< "$identity"
	local parent_pid="${HARD_TIMEOUT_PARENT_PID:-0}"
	local parent_start=0
	if [[ "$parent_pid" != "0" ]]; then
		local parent_identity=""
		local _parent_boot _parent_namespace
		parent_identity="$(read_process_identity "$parent_pid")" || return 1
		read -r _parent_boot _parent_namespace parent_start <<< "$parent_identity"
	fi
	if [[ "${HARD_TIMEOUT_TEST_REGISTRATION_FAILURE:-0}" == "1" ]]; then
		local wait_file="${HARD_TIMEOUT_TEST_REGISTRATION_FAILURE_WAIT_FILE:-}"
		local entered_file="${HARD_TIMEOUT_TEST_REGISTRATION_FAILURE_ENTERED_FILE:-}"
		local deferred_signal_file="${HARD_TIMEOUT_TEST_DEFERRED_SIGNAL_FILE:-}"
		local wait_ns=1000000000
		if [[ -n "$entered_file" && -n "$deferred_signal_file" ]]; then
			printf 'entered\n' > "$entered_file" || return 1
			wait_ns=5000000000
		fi
		local wait_deadline=$(( $(date +%s%N) + wait_ns ))
		while [[ -n "$wait_file" && ! -s "$wait_file" && ! -s "$deferred_signal_file" && \
			$(date +%s%N) -lt $wait_deadline ]]; do
			sleep 0.01
		done
		return 1
	fi
	validate_hard_timeout_registry || return 1
	local record="$HARD_TIMEOUT_REGISTRY_ROOT/$pid.$BASHPID.record"
	local temporary=""
	temporary="$(mktemp "$HARD_TIMEOUT_REGISTRY_ROOT/.record.XXXXXX")" || return 1
	if ! printf 'v1 %s %s %s %s %s %s %s\n' \
		"$pid" "$pgid" "$parent_pid" "$parent_start" "$boot_id" "$pid_namespace" "$start_time" > "$temporary" || \
		! mv "$temporary" "$record"; then
		rm -f "$temporary"
		return 1
	fi
	HARD_TIMEOUT_ACTIVE_PIDS+=("$pid")
	HARD_TIMEOUT_ACTIVE_PGIDS+=("$pgid")
	HARD_TIMEOUT_ACTIVE_RECORDS+=("$record")
	HARD_TIMEOUT_ACTIVE_START_TIMES+=("$start_time")
	HARD_TIMEOUT_ACTIVE_BOOT_IDS+=("$boot_id")
	HARD_TIMEOUT_ACTIVE_PID_NAMESPACES+=("$pid_namespace")
	if [[ -n "${HARD_TIMEOUT_TRACE_FILE:-}" ]]; then
		printf '%s %s %s %s\n' "$gate_name" "$pid" "$pgid" "$parent_pid" >> "$HARD_TIMEOUT_TRACE_FILE"
	fi
	HARD_TIMEOUT_LAST_RECORD="$record"
	HARD_TIMEOUT_LAST_START_TIME="$start_time"
	HARD_TIMEOUT_LAST_BOOT_ID="$boot_id"
	HARD_TIMEOUT_LAST_PID_NAMESPACE="$pid_namespace"
}

read_timeout_record() {
	local record="$1"
	local version extra
	TIMEOUT_RECORD_PID=""
	TIMEOUT_RECORD_PGID=""
	TIMEOUT_RECORD_PARENT_PID=""
	TIMEOUT_RECORD_PARENT_START=""
	TIMEOUT_RECORD_BOOT_ID=""
	TIMEOUT_RECORD_PID_NAMESPACE=""
	TIMEOUT_RECORD_START_TIME=""
	if [[ ! -e "$record" ]]; then
		return 2
	fi
	if [[ ! -f "$record" || -L "$record" ]]; then
		return 1
	fi
	if ! read -r version TIMEOUT_RECORD_PID TIMEOUT_RECORD_PGID TIMEOUT_RECORD_PARENT_PID \
			TIMEOUT_RECORD_PARENT_START TIMEOUT_RECORD_BOOT_ID TIMEOUT_RECORD_PID_NAMESPACE \
			TIMEOUT_RECORD_START_TIME extra < "$record"; then
		[[ ! -e "$record" ]] && return 2
		return 1
	fi
	if [[ "$version" != "v1" || -n "${extra:-}" || \
		! "$TIMEOUT_RECORD_PID" =~ ^[1-9][0-9]*$ || \
		! "$TIMEOUT_RECORD_PGID" =~ ^[1-9][0-9]*$ || \
		! "$TIMEOUT_RECORD_PARENT_PID" =~ ^[0-9]+$ || \
		! "$TIMEOUT_RECORD_PARENT_START" =~ ^[0-9]+$ || \
		! "$TIMEOUT_RECORD_BOOT_ID" =~ ^[0-9a-fA-F-]+$ || \
		! "$TIMEOUT_RECORD_PID_NAMESPACE" =~ ^pid:\[[0-9]+\]$ || \
		! "$TIMEOUT_RECORD_START_TIME" =~ ^[0-9]+$ ]]; then
		return 1
	fi
}

remove_active_timeout() {
	local completed_pid="$1"
	local remaining_pids=()
	local remaining_pgids=()
	local remaining_records=()
	local remaining_starts=()
	local remaining_boots=()
	local remaining_namespaces=()
	local index
	for ((index = 0; index < ${#HARD_TIMEOUT_ACTIVE_PIDS[@]}; index += 1)); do
		if [[ "${HARD_TIMEOUT_ACTIVE_PIDS[$index]}" != "$completed_pid" ]]; then
			remaining_pids+=("${HARD_TIMEOUT_ACTIVE_PIDS[$index]}")
			remaining_pgids+=("${HARD_TIMEOUT_ACTIVE_PGIDS[$index]}")
			remaining_records+=("${HARD_TIMEOUT_ACTIVE_RECORDS[$index]}")
			remaining_starts+=("${HARD_TIMEOUT_ACTIVE_START_TIMES[$index]}")
			remaining_boots+=("${HARD_TIMEOUT_ACTIVE_BOOT_IDS[$index]}")
			remaining_namespaces+=("${HARD_TIMEOUT_ACTIVE_PID_NAMESPACES[$index]}")
		fi
	done
	HARD_TIMEOUT_ACTIVE_PIDS=("${remaining_pids[@]}")
	HARD_TIMEOUT_ACTIVE_PGIDS=("${remaining_pgids[@]}")
	HARD_TIMEOUT_ACTIVE_RECORDS=("${remaining_records[@]}")
	HARD_TIMEOUT_ACTIVE_START_TIMES=("${remaining_starts[@]}")
	HARD_TIMEOUT_ACTIVE_BOOT_IDS=("${remaining_boots[@]}")
	HARD_TIMEOUT_ACTIVE_PID_NAMESPACES=("${remaining_namespaces[@]}")
}

cleanup_registered_timeout_descendants() {
	local parent_pid="$1"
	local parent_start="$2"
	local grace_seconds="$3"
	local max_nodes="${HARD_TIMEOUT_REGISTRY_MAX_NODES:-128}"
	local max_depth="${HARD_TIMEOUT_REGISTRY_MAX_DEPTH:-16}"
	validate_hard_timeout_registry || return 1

	local -a record_paths=()
	mapfile -t record_paths < <(find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f -name '*.record' -print | LC_ALL=C sort)
	local -a parsed_record_paths=() pids=() pgids=() parents=() parent_starts=() boots=() namespaces=() starts=()
	local record=""
	for record in "${record_paths[@]}"; do
		local record_status=0
		read_timeout_record "$record" || record_status=$?
		if [[ "$record_status" -eq 2 ]]; then
			continue
		fi
		if [[ "$record_status" -ne 0 ]]; then
			echo "Malformed timeout registry record: $record" >&2
			return 1
		fi
		parsed_record_paths+=("$record")
		pids+=("$TIMEOUT_RECORD_PID")
		pgids+=("$TIMEOUT_RECORD_PGID")
		parents+=("$TIMEOUT_RECORD_PARENT_PID")
		parent_starts+=("$TIMEOUT_RECORD_PARENT_START")
		boots+=("$TIMEOUT_RECORD_BOOT_ID")
		namespaces+=("$TIMEOUT_RECORD_PID_NAMESPACE")
		starts+=("$TIMEOUT_RECORD_START_TIME")
	done

	local -a queue_pids=("$parent_pid") queue_starts=("$parent_start") queue_depths=(0)
	local -a selected=()
	local queue_index=0
	local child_index child_depth key
	declare -A visited=( ["$parent_pid:$parent_start"]=1 )
	while (( queue_index < ${#queue_pids[@]} )); do
		for ((child_index = 0; child_index < ${#pids[@]}; child_index += 1)); do
			if [[ "${parents[$child_index]}" != "${queue_pids[$queue_index]}" || \
				"${parent_starts[$child_index]}" != "${queue_starts[$queue_index]}" ]]; then
				continue
			fi
			child_depth=$((queue_depths[$queue_index] + 1))
			key="${pids[$child_index]}:${starts[$child_index]}"
			if [[ -n "${visited[$key]:-}" ]]; then
				echo "Cycle or duplicate identity in timeout registry: $key" >&2
				return 1
			fi
			if (( child_depth > max_depth || ${#selected[@]} >= max_nodes )); then
				echo "Timeout registry traversal bound exceeded: depth=$child_depth nodes=${#selected[@]}" >&2
				return 1
			fi
			visited[$key]=1
			selected+=("$child_index")
			queue_pids+=("${pids[$child_index]}")
			queue_starts+=("${starts[$child_index]}")
			queue_depths+=("$child_depth")
		done
		queue_index=$((queue_index + 1))
	done

	local cleanup_status=0
	local selection_index
	for ((selection_index = ${#selected[@]} - 1; selection_index >= 0; selection_index -= 1)); do
		child_index="${selected[$selection_index]}"
		local termination_status=0
		terminate_timeout_identity \
			"${pids[$child_index]}" "${pgids[$child_index]}" "${boots[$child_index]}" \
			"${namespaces[$child_index]}" "${starts[$child_index]}" "$grace_seconds" || termination_status=$?
		if [[ "$termination_status" -eq 0 ]]; then
			rm -f "${parsed_record_paths[$child_index]}"
		elif timeout_identity_confirmed_gone \
			"${pids[$child_index]}" "${boots[$child_index]}" \
			"${namespaces[$child_index]}" "${starts[$child_index]}"; then
			rm -f "${parsed_record_paths[$child_index]}"
			cleanup_status=1
		else
			cleanup_status=1
		fi
	done
	return "$cleanup_status"
}

cleanup_hard_timeout_processes() {
	local grace_seconds="${HARD_TIMEOUT_CLEANUP_GRACE_SECONDS:-1}"
	local cleanup_status=0
	local active_pids=("${HARD_TIMEOUT_ACTIVE_PIDS[@]}")
	local active_pgids=("${HARD_TIMEOUT_ACTIVE_PGIDS[@]}")
	local active_records=("${HARD_TIMEOUT_ACTIVE_RECORDS[@]}")
	local active_starts=("${HARD_TIMEOUT_ACTIVE_START_TIMES[@]}")
	local active_boots=("${HARD_TIMEOUT_ACTIVE_BOOT_IDS[@]}")
	local active_namespaces=("${HARD_TIMEOUT_ACTIVE_PID_NAMESPACES[@]}")
	local index
	for ((index = 0; index < ${#active_pids[@]}; index += 1)); do
		cleanup_registered_timeout_descendants "${active_pids[$index]}" "${active_starts[$index]}" "$grace_seconds" || cleanup_status=1
		local termination_status=0
		terminate_timeout_identity "${active_pids[$index]}" "${active_pgids[$index]}" \
			"${active_boots[$index]}" "${active_namespaces[$index]}" "${active_starts[$index]}" "$grace_seconds" || termination_status=$?
		if [[ "$termination_status" -eq 0 ]]; then
			rm -f "${active_records[$index]}"
			remove_active_timeout "${active_pids[$index]}"
		elif timeout_identity_confirmed_gone \
			"${active_pids[$index]}" "${active_boots[$index]}" \
			"${active_namespaces[$index]}" "${active_starts[$index]}"; then
			rm -f "${active_records[$index]}"
			remove_active_timeout "${active_pids[$index]}"
			cleanup_status=1
		else
			cleanup_status=1
		fi
	done

	if [[ -d "${HARD_TIMEOUT_REGISTRY_ROOT:-}" ]]; then
		local registry_lock_fd
		exec {registry_lock_fd}<"$HARD_TIMEOUT_REGISTRY_ROOT" || return 1
		flock -x "$registry_lock_fd" || {
			exec {registry_lock_fd}<&-
			return 1
		}
		if [[ "${#HARD_TIMEOUT_ACTIVE_PIDS[@]}" -eq 0 ]]; then
			release_hard_timeout_registry_owner
		fi
		local live_owner_count=0
		local owner_record=""
		while IFS= read -r owner_record; do
			local owner_version owner_pid owner_boot owner_namespace owner_start owner_extra
			if ! read -r owner_version owner_pid owner_boot owner_namespace owner_start owner_extra < "$owner_record" || \
				[[ "$owner_version" != "v1" || -n "${owner_extra:-}" || ! "$owner_pid" =~ ^[1-9][0-9]*$ || \
				! "$owner_boot" =~ ^[0-9a-fA-F-]+$ || ! "$owner_namespace" =~ ^pid:\[[0-9]+\]$ || ! "$owner_start" =~ ^[0-9]+$ ]]; then
				echo "Malformed timeout registry owner lease: $owner_record" >&2
				cleanup_status=1
				continue
			fi
			if process_identity_matches "$owner_pid" "$owner_boot" "$owner_namespace" "$owner_start"; then
				live_owner_count=$((live_owner_count + 1))
			else
				rm -f "$owner_record"
			fi
		done < <(find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f -name '.owner.*' -print | LC_ALL=C sort)
		local pending_completion_count=0
		local pending_record=""
		while IFS= read -r pending_record; do
			local pending_version pending_pid pending_boot pending_namespace pending_start
			local prereg_pid prereg_pgid prereg_boot prereg_namespace prereg_start pending_extra
			if ! read -r pending_version pending_pid pending_boot pending_namespace pending_start \
					prereg_pid prereg_pgid prereg_boot prereg_namespace prereg_start pending_extra < "$pending_record" || \
				[[ "$pending_version" != "v1" && "$pending_version" != "v2" ]] || \
				[[ ! "$pending_pid" =~ ^[1-9][0-9]*$ || ! "$pending_boot" =~ ^[0-9a-fA-F-]+$ || \
				! "$pending_namespace" =~ ^pid:\[[0-9]+\]$ || ! "$pending_start" =~ ^[0-9]+$ ]]; then
				echo "Malformed timeout pending-completion record: $pending_record" >&2
				cleanup_status=1
				pending_completion_count=$((pending_completion_count + 1))
				continue
			fi
			if [[ "$pending_version" == "v1" ]]; then
				if [[ -n "${prereg_pid:-}" || -n "${prereg_pgid:-}" || -n "${prereg_boot:-}" || \
					-n "${prereg_namespace:-}" || -n "${prereg_start:-}" || -n "${pending_extra:-}" ]]; then
					echo "Malformed timeout pending-completion record: $pending_record" >&2
					cleanup_status=1
					pending_completion_count=$((pending_completion_count + 1))
					continue
				fi
				if process_identity_matches "$pending_pid" "$pending_boot" "$pending_namespace" "$pending_start"; then
					pending_completion_count=$((pending_completion_count + 1))
				else
					rm -f "$pending_record"
				fi
				continue
			fi
			if [[ -n "${pending_extra:-}" || ! "$prereg_pid" =~ ^[1-9][0-9]*$ || \
				! "$prereg_pgid" =~ ^[1-9][0-9]*$ || ! "$prereg_boot" =~ ^[0-9a-fA-F-]+$ || \
				! "$prereg_namespace" =~ ^pid:\[[0-9]+\]$ || ! "$prereg_start" =~ ^[0-9]+$ ]]; then
				echo "Malformed timeout preregistration identity: $pending_record" >&2
				cleanup_status=1
				pending_completion_count=$((pending_completion_count + 1))
				continue
			fi
			if process_identity_matches "$pending_pid" "$pending_boot" "$pending_namespace" "$pending_start" && \
				[[ "$pending_pid" != "$BASHPID" ]]; then
				pending_completion_count=$((pending_completion_count + 1))
				continue
			fi
			local prereg_termination_status=0
			if process_identity_matches "$prereg_pid" "$prereg_boot" "$prereg_namespace" "$prereg_start"; then
				cleanup_registered_timeout_descendants "$prereg_pid" "$prereg_start" "$grace_seconds" || cleanup_status=1
				terminate_timeout_identity "$prereg_pid" "$prereg_pgid" "$prereg_boot" \
					"$prereg_namespace" "$prereg_start" "$grace_seconds" || prereg_termination_status=$?
			elif timeout_identity_confirmed_gone "$prereg_pid" "$prereg_boot" "$prereg_namespace" "$prereg_start"; then
				prereg_termination_status=0
			else
				prereg_termination_status=1
			fi
			if [[ "$prereg_termination_status" -eq 0 ]]; then
				rm -f "$pending_record"
			else
				cleanup_status=1
				pending_completion_count=$((pending_completion_count + 1))
			fi
		done < <(find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f -name '.pending.*' -print | LC_ALL=C sort)
		if [[ "$live_owner_count" -ne 0 || "$pending_completion_count" -ne 0 ]]; then
			exec {registry_lock_fd}<&-
			return "$cleanup_status"
		fi
		local -a remaining_records=()
		mapfile -t remaining_records < <(find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f -name '*.record' -print | LC_ALL=C sort)
		local record
		for record in "${remaining_records[@]}"; do
			local record_status=0
			read_timeout_record "$record" || record_status=$?
			if [[ "$record_status" -eq 2 ]]; then
				continue
			fi
			if [[ "$record_status" -ne 0 ]]; then
				echo "Malformed timeout registry record during owner cleanup: $record" >&2
				cleanup_status=1
				continue
			fi
			# Descendant traversal parses every record, so freeze this record's
			# identity before any nested parser call can overwrite TIMEOUT_RECORD_*.
			local record_pid="$TIMEOUT_RECORD_PID"
			local record_pgid="$TIMEOUT_RECORD_PGID"
			local record_boot="$TIMEOUT_RECORD_BOOT_ID"
			local record_namespace="$TIMEOUT_RECORD_PID_NAMESPACE"
			local record_start="$TIMEOUT_RECORD_START_TIME"
			cleanup_registered_timeout_descendants "$record_pid" "$record_start" "$grace_seconds" || cleanup_status=1
			local termination_status=0
			terminate_timeout_identity "$record_pid" "$record_pgid" \
				"$record_boot" "$record_namespace" "$record_start" "$grace_seconds" || termination_status=$?
			if [[ "$termination_status" -eq 0 ]]; then
				rm -f "$record"
			elif timeout_identity_confirmed_gone "$record_pid" "$record_boot" "$record_namespace" "$record_start"; then
				rm -f "$record"
				cleanup_status=1
			else
				cleanup_status=1
			fi
		done
		local remaining_record_count=0
		remaining_record_count="$(find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f -name '*.record' | wc -l)"
		if [[ "$remaining_record_count" -eq 0 && "${#HARD_TIMEOUT_ACTIVE_PIDS[@]}" -eq 0 ]]; then
			find "$HARD_TIMEOUT_REGISTRY_ROOT" -mindepth 1 -maxdepth 1 -type f \
				\( -name '.spawn.*' -o -name '.handshake.*' -o -name '.record.*' -o -name '.pending-record.*' -o -name '.owner-record.*' -o -name '.owner.*' \) -delete
			if rmdir "$HARD_TIMEOUT_REGISTRY_ROOT"; then
				unset HARD_TIMEOUT_REGISTRY_ROOT HARD_TIMEOUT_REGISTRY_OWNER_PID
			else
				echo "Timeout registry retained because unknown entries remain: $HARD_TIMEOUT_REGISTRY_ROOT" >&2
				cleanup_status=1
			fi
		fi
		exec {registry_lock_fd}<&-
	else
		HARD_TIMEOUT_OWNER_LEASE=""
		HARD_TIMEOUT_OWNER_START_TIME=""
		HARD_TIMEOUT_OWNER_BOOT_ID=""
		HARD_TIMEOUT_OWNER_PID_NAMESPACE=""
	fi
	return "$cleanup_status"
}

run_with_hard_timeout() {
	local gate_name="$1"
	local timeout_seconds="$2"
	local kill_after_seconds="$3"
	shift 3

	if [[ ! "$timeout_seconds" =~ ^[1-9][0-9]*$ ]] || [[ ! "$kill_after_seconds" =~ ^[1-9][0-9]*$ ]]; then
		echo "Invalid timeout for $gate_name: timeout=$timeout_seconds kill_after=$kill_after_seconds" >&2
		return 2
	fi
	if ! command -v timeout >/dev/null 2>&1 || ! command -v setsid >/dev/null 2>&1; then
		echo "GNU timeout and setsid are required for $gate_name." >&2
		return 2
	fi
	if ! ensure_hard_timeout_registry; then
		echo "Timeout registry preflight failed before spawning $gate_name." >&2
		return 72
	fi
	local pending_completion=""
	pending_completion="$(mktemp "$HARD_TIMEOUT_REGISTRY_ROOT/.pending.$BASHPID.XXXXXX")" || {
		echo "Timeout registry could not record pending completion for $gate_name." >&2
		return 72
	}
	printf 'v1 %s %s %s %s\n' "$BASHPID" "$HARD_TIMEOUT_OWNER_BOOT_ID" "$HARD_TIMEOUT_OWNER_PID_NAMESPACE" "$HARD_TIMEOUT_OWNER_START_TIME" > "$pending_completion" || {
		rm -f "$pending_completion"
		return 72
	}

	echo "TIMEOUT_GATE_START gate=$gate_name timeout=${timeout_seconds}s kill_after=${kill_after_seconds}s"
	local spawn_handshake="$HARD_TIMEOUT_REGISTRY_ROOT/.spawn.$BASHPID.$RANDOM"
	local spawn_ack="$spawn_handshake.ack"
	local completion_file="$spawn_handshake.complete"
	local status=0
	local deferred_registration_signal=""
	local previous_term_trap=""
	local previous_int_trap=""
	previous_term_trap="$(trap -p TERM || true)"
	previous_int_trap="$(trap -p INT || true)"
	trap 'deferred_registration_signal=TERM; if [[ -n "${HARD_TIMEOUT_TEST_DEFERRED_SIGNAL_FILE:-}" ]]; then printf "TERM\n" > "$HARD_TIMEOUT_TEST_DEFERRED_SIGNAL_FILE" || true; fi' TERM
	trap 'deferred_registration_signal=INT; if [[ -n "${HARD_TIMEOUT_TEST_DEFERRED_SIGNAL_FILE:-}" ]]; then printf "INT\n" > "$HARD_TIMEOUT_TEST_DEFERRED_SIGNAL_FILE" || true; fi' INT
	setsid bash -c '
		timeout_seconds="$1"
		kill_after_seconds="$2"
		spawn_handshake="$3"
		spawn_ack="$4"
		completion_file="$5"
		parent_pid="$6"
		shift 6
		trap ":" TERM INT
		trap "exit 0" USR1
		printf "%s\n" "$BASHPID" > "$spawn_handshake" || exit 72
		while [[ ! -s "$spawn_ack" ]]; do
			if ! kill -0 "$PPID" 2>/dev/null; then
				exit 72
			fi
			sleep 0.01
		done
		ack="$(<"$spawn_ack")"
		rm -f "$spawn_handshake" "$spawn_ack"
		if [[ "$ack" != "go" ]]; then
			while kill -0 "$parent_pid" 2>/dev/null; do sleep 0.02; done
			exit 72
		fi
		export HARD_TIMEOUT_PARENT_PID="$BASHPID"
		command_status=0
		timeout --foreground --signal=TERM --kill-after="${kill_after_seconds}s" "${timeout_seconds}s" "$@" || command_status=$?
		if [[ -n "${HARD_TIMEOUT_TEST_COMPLETION_READY_FILE:-}" ]]; then
			printf "%s\n" ready > "$HARD_TIMEOUT_TEST_COMPLETION_READY_FILE" || exit 72
			while [[ ! -s "${HARD_TIMEOUT_TEST_COMPLETION_RELEASE_FILE:-}" ]]; do
				if ! kill -0 "$parent_pid" 2>/dev/null; then
					exit 72
				fi
				sleep 0.01
			done
		fi
		temporary="${completion_file}.tmp.$BASHPID"
		printf "%s\n" "$command_status" > "$temporary" || exit 72
		mv "$temporary" "$completion_file" || exit 72
		if [[ -n "${HARD_TIMEOUT_TEST_COMPLETION_LANDED_FILE:-}" ]]; then
			printf "%s\n" "$command_status" > "$HARD_TIMEOUT_TEST_COMPLETION_LANDED_FILE" || exit 72
		fi
		while kill -0 "$parent_pid" 2>/dev/null; do sleep 0.02; done
		exit 72
	' timeout-supervisor "$timeout_seconds" "$kill_after_seconds" "$spawn_handshake" "$spawn_ack" "$completion_file" "$BASHPID" "$@" &
	local timeout_pid=$!
	local timeout_pgid=""
	local spawn_identity=""
	local boot_id=""
	local pid_namespace=""
	local start_time=""
	local preregistration_status=0
	timeout_pgid="$(read_process_group "$timeout_pid")" || preregistration_status=1
	spawn_identity="$(read_process_identity "$timeout_pid")" || preregistration_status=1
	if [[ "$preregistration_status" -eq 0 ]]; then
		read -r boot_id pid_namespace start_time <<< "$spawn_identity"
		promote_pending_timeout_identity "$pending_completion" "$timeout_pid" "$timeout_pgid" \
			"$boot_id" "$pid_namespace" "$start_time" || preregistration_status=1
	fi
	if [[ "$preregistration_status" -ne 0 ]]; then
		local unregistered_cleanup_status=0
		terminate_unregistered_timeout_child "$timeout_pid" "$kill_after_seconds" || unregistered_cleanup_status=1
		rm -f "$spawn_handshake" "$spawn_ack" "$completion_file" "$completion_file".tmp.* "$pending_completion"
		cleanup_hard_timeout_processes || unregistered_cleanup_status=1
		restore_hard_timeout_signal_trap TERM "$previous_term_trap"
		restore_hard_timeout_signal_trap INT "$previous_int_trap"
		echo "Timeout process identity could not be persisted after spawning $gate_name." >&2
		if [[ -n "$deferred_registration_signal" ]]; then
			local forwarded_status=0
			forward_hard_timeout_signal "$deferred_registration_signal" || forwarded_status=$?
			return "$forwarded_status"
		fi
		[[ "$unregistered_cleanup_status" -eq 0 ]] && return 72
		return 71
	fi
	local handshake_deadline=$(( $(date +%s%N) + 1000000000 ))
	while [[ ! -s "$spawn_handshake" && $(date +%s%N) -lt $handshake_deadline ]]; do
		if ! process_exists "$timeout_pid"; then
			break
		fi
		sleep 0.01
	done
	if [[ ! -s "$spawn_handshake" ]]; then
		terminate_timeout_identity "$timeout_pid" "$timeout_pgid" "$boot_id" "$pid_namespace" "$start_time" "$kill_after_seconds" || true
		rm -f "$spawn_handshake" "$spawn_ack" "$completion_file" "$completion_file".tmp.* "$pending_completion"
		cleanup_hard_timeout_processes || true
		restore_hard_timeout_signal_trap TERM "$previous_term_trap"
		restore_hard_timeout_signal_trap INT "$previous_int_trap"
		echo "Timeout process handshake failed after spawning $gate_name." >&2
		if [[ -n "$deferred_registration_signal" ]]; then
			local forwarded_status=0
			forward_hard_timeout_signal "$deferred_registration_signal" || forwarded_status=$?
			return "$forwarded_status"
		fi
		return 72
	fi
	if [[ -n "${HARD_TIMEOUT_TEST_SPAWN_PID_FILE:-}" ]]; then
		printf '%s\n' "$timeout_pid" > "$HARD_TIMEOUT_TEST_SPAWN_PID_FILE"
		printf '%s\n' "$timeout_pgid" > "$HARD_TIMEOUT_TEST_SPAWN_PID_FILE.pgid"
	fi
	if [[ "${HARD_TIMEOUT_TEST_REGISTRY_DELETE_AFTER_SPAWN:-0}" == "1" ]]; then
		rm -rf "$HARD_TIMEOUT_REGISTRY_ROOT"
	fi
	if ! register_timeout_process "$gate_name" "$timeout_pid" "$timeout_pgid"; then
		{ printf '%s\n' stop > "$spawn_ack"; } 2>/dev/null || true
		local registration_cleanup_status=0
		terminate_timeout_identity "$timeout_pid" "$timeout_pgid" "$boot_id" "$pid_namespace" "$start_time" "$kill_after_seconds" || registration_cleanup_status=1
		if [[ "$registration_cleanup_status" -eq 0 ]] || timeout_identity_confirmed_gone \
			"$timeout_pid" "$boot_id" "$pid_namespace" "$start_time"; then
			rm -f "$pending_completion"
		fi
		rm -f "$spawn_handshake" "$spawn_ack" "$completion_file" "$completion_file".tmp.*
		cleanup_hard_timeout_processes || registration_cleanup_status=1
		restore_hard_timeout_signal_trap TERM "$previous_term_trap"
		restore_hard_timeout_signal_trap INT "$previous_int_trap"
		echo "Timeout process registration failed after spawning $gate_name; spawned tree was reaped." >&2
		if [[ -n "$deferred_registration_signal" ]]; then
			local forwarded_status=0
			forward_hard_timeout_signal "$deferred_registration_signal" || forwarded_status=$?
			return "$forwarded_status"
		fi
		[[ "$registration_cleanup_status" -eq 0 ]] && return 72
		return 71
	fi
	local record="$HARD_TIMEOUT_LAST_RECORD"
	start_time="$HARD_TIMEOUT_LAST_START_TIME"
	boot_id="$HARD_TIMEOUT_LAST_BOOT_ID"
	pid_namespace="$HARD_TIMEOUT_LAST_PID_NAMESPACE"
	if ! demote_pending_timeout_identity "$pending_completion"; then
		local pending_demote_cleanup_status=0
		cleanup_hard_timeout_processes || pending_demote_cleanup_status=1
		restore_hard_timeout_signal_trap TERM "$previous_term_trap"
		restore_hard_timeout_signal_trap INT "$previous_int_trap"
		if [[ -n "$deferred_registration_signal" ]]; then
			local forwarded_status=0
			forward_hard_timeout_signal "$deferred_registration_signal" || forwarded_status=$?
			return "$forwarded_status"
		fi
		[[ "$pending_demote_cleanup_status" -eq 0 ]] && return 72
		return 71
	fi
	restore_hard_timeout_signal_trap TERM "$previous_term_trap"
	restore_hard_timeout_signal_trap INT "$previous_int_trap"
	if [[ -n "$deferred_registration_signal" ]]; then
		local deferred_cleanup_status=0
		cleanup_hard_timeout_processes || deferred_cleanup_status=1
		local forwarded_status=0
		forward_hard_timeout_signal "$deferred_registration_signal" || forwarded_status=$?
		[[ "$deferred_cleanup_status" -eq 0 ]] && return "$forwarded_status"
		return 71
	fi
	if ! { printf '%s\n' go > "$spawn_ack"; } 2>/dev/null; then
		terminate_timeout_identity "$timeout_pid" "$timeout_pgid" "$boot_id" "$pid_namespace" "$start_time" "$kill_after_seconds" || true
		rm -f "$record" "$spawn_handshake" "$spawn_ack" "$completion_file" "$completion_file".tmp.* "$pending_completion"
		remove_active_timeout "$timeout_pid"
		return 72
	fi
	echo "TIMEOUT_GATE_PROCESS gate=$gate_name pid=$timeout_pid pgid=$timeout_pgid"
	local completion_deadline=$(( $(date +%s%N) + (timeout_seconds + kill_after_seconds + 2) * 1000000000 ))
	while [[ ! -s "$completion_file" ]]; do
		if ! process_exists "$timeout_pid" || (( $(date +%s%N) >= completion_deadline )); then
			status=71
			break
		fi
		sleep 0.02
	done
	if [[ "$status" -ne 71 ]]; then
		IFS= read -r status < "$completion_file" || status=71
		if [[ ! "$status" =~ ^[0-9]+$ || "$status" -gt 255 ]]; then
			status=71
		fi
	fi

	local cleanup_status=0
	cleanup_registered_timeout_descendants "$timeout_pid" "$start_time" "$kill_after_seconds" || cleanup_status=1
	terminate_timeout_identity "$timeout_pid" "$timeout_pgid" "$boot_id" "$pid_namespace" "$start_time" "$kill_after_seconds" || cleanup_status=1
	rm -f "$record" "$completion_file" "$completion_file".tmp.* "$pending_completion"
	remove_active_timeout "$timeout_pid"
	if [[ "$cleanup_status" -ne 0 ]]; then
		return 71
	fi
	if [[ "$status" -eq 124 || "$status" -eq 137 ]]; then
		echo "TIMEOUT_GATE_EXPIRED gate=$gate_name status=$status timeout=${timeout_seconds}s" >&2
	fi
	return "$status"
}
